/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ChiTietHoaDDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiTietHoaDon;

/**
 *
 * @author ADMIN
 */
public class CTHD extends javax.swing.JPanel {

    ChiTietHoaDDAO billDetailDAO = new ChiTietHoaDDAO();
    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form CTHD
     */
    public CTHD() {
        initComponents();
        initTable();
        fillToTable();
    }

    public void reset() {
        txtDongia.setText("");
        txtMaCTHD.setText("");
        txtMaHD.setText("");
        txtMaCTSP.setText("");
        txtMaKM.setText("");
        txtTenSP.setText("");
        txtTrangthai.setText("");
    }

    public boolean checkForm() {
        if (txtDongia.getText().isEmpty() && txtMaCTHD.getText().isEmpty() && txtMaCTSP.getText().isEmpty() && txtMaHD.getText().isEmpty()
                && txtMaKM.getText().isEmpty() && txtTenSP.getText().isEmpty() && txtTrangthai.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    public void add() {
        try {
            if (checkForm()) {
                double donGia = Double.parseDouble(txtDongia.getText());
                String maCTHD = txtMaCTHD.getText();
                String maHD = txtMaCTSP.getText();
                String maCTSP = txtMaCTSP.getText();
                String maKM = txtMaKM.getText();
                String tenSP = txtTenSP.getText();
                String trangThai = txtTrangthai.getText();
                int result = billDetailDAO.create(new ChiTietHoaDon(maCTHD, maHD, maKM, maCTSP, tenSP, donGia, trangThai));
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công!!!", "NOTITFICATION!!!", JOptionPane.INFORMATION_MESSAGE);
                    fillToTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm lỗi!!!", "NOTIFICATION!!!", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!!!", "NOTIFICATION!!!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "NOTIFICATION!!!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void initTable() {
        String column[] = {"MaCTHD", "MaHD", "MaKM", "MaCTSP", "TenSP", "DonGia", "TrangThai"};
        tableModel.setColumnIdentifiers(column);
        tblCTHD.setModel(tableModel);
    }

    public void fillToTable() {
        tableModel.setRowCount(0);
        for (ChiTietHoaDon detail : billDetailDAO.read()) {
            tableModel.addRow(billDetailDAO.getRow(detail));
        }
    }

    public void showDetail() {
        int index = tblCTHD.getSelectedRow();
        ChiTietHoaDon billDetail = billDetailDAO.read().get(index);
        txtDongia.setText(String.valueOf(billDetail.getDonGia()));
        txtMaCTHD.setText(billDetail.getMaCTHD());
        txtMaCTSP.setText(billDetail.getMaCTSP());
        txtMaHD.setText(billDetail.getMaHD());
        txtMaKM.setText(billDetail.getMaKM());
        txtTenSP.setText(billDetail.getTenSP());
        txtTrangthai.setText(billDetail.getTrangThai());
    }

    public void update() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLammoi = new javax.swing.JButton();
        lbMaCTHD = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        lbMaHD = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        txtMaCTSP = new javax.swing.JTextField();
        lbTrangthai = new javax.swing.JLabel();
        lbDongia = new javax.swing.JLabel();
        txtMaCTHD = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        lbSoluong = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        lbCTHD = new javax.swing.JLabel();
        lbMaCTSP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTHD = new javax.swing.JTable();
        txtTrangthai = new javax.swing.JTextField();

        btnLammoi.setText("LÀM MỚI");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        lbMaCTHD.setText("Mã CTHD:");

        lbMaNV.setText("Mã KM:");

        lbMaHD.setText("Mã HD:");

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });

        lbTrangthai.setText("Trạng thái:");

        lbDongia.setText("Đơn giá:");

        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        lbSoluong.setText("Tên SP:");

        lbCTHD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbCTHD.setForeground(new java.awt.Color(0, 0, 255));
        lbCTHD.setText("CHI TIẾT HÓA ĐƠN");

        lbMaCTSP.setText("Mã CTSP:");

        tblCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTHD);

        txtTrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrangthaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lbCTHD))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTrangthai)
                                    .addComponent(lbDongia))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbSoluong)
                                    .addComponent(lbMaNV)
                                    .addComponent(lbMaCTHD)
                                    .addComponent(lbMaCTSP)
                                    .addComponent(lbMaHD))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMaCTSP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaKM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaCTHD, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88)
                        .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbCTHD)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaCTHD))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaHD)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLammoi))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNV)
                    .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaCTSP)
                    .addComponent(txtMaCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTrangthai)
                    .addComponent(txtTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDongia)
                    .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void txtTrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrangthaiActionPerformed

    private void tblCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHDMouseClicked
        // TODO add your handling code here:
        showDetail();
        fillToTable();

    }//GEN-LAST:event_tblCTHDMouseClicked

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnLammoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCTHD;
    private javax.swing.JLabel lbDongia;
    private javax.swing.JLabel lbMaCTHD;
    private javax.swing.JLabel lbMaCTSP;
    private javax.swing.JLabel lbMaHD;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JLabel lbTrangthai;
    private javax.swing.JTable tblCTHD;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtMaCTHD;
    private javax.swing.JTextField txtMaCTSP;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTrangthai;
    // End of variables declaration//GEN-END:variables
}
