/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ADMIN
 */
public class MENU extends javax.swing.JPanel {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAococ = new javax.swing.JPanel();
        btnAococ = new javax.swing.JButton();
        lbAococ1 = new javax.swing.JLabel();
        lbAococ = new javax.swing.JLabel();
        lbMenu = new javax.swing.JLabel();
        pnAokhoac = new javax.swing.JPanel();
        btnAokhoac = new javax.swing.JButton();
        lbAokhoac1 = new javax.swing.JLabel();
        lbAokhoac = new javax.swing.JLabel();
        pnAoni = new javax.swing.JPanel();
        lbAoni1 = new javax.swing.JLabel();
        lbAoni = new javax.swing.JLabel();
        btnAoni = new javax.swing.JButton();
        pnAosomi = new javax.swing.JPanel();
        btnAosomi = new javax.swing.JButton();
        lbAosomi1 = new javax.swing.JLabel();
        lbAosomi = new javax.swing.JLabel();
        pnAococ1 = new javax.swing.JPanel();
        btnAococ1 = new javax.swing.JButton();
        lbAococ2 = new javax.swing.JLabel();
        lbAococ3 = new javax.swing.JLabel();
        lbMenu1 = new javax.swing.JLabel();

        pnAococ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAococ.setText("Xem chi tiết");
        btnAococ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAococActionPerformed(evt);
            }
        });

        lbAococ1.setText("Áo cộc");

        lbAococ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Anh4.png"))); // NOI18N
        lbAococ.setText("jLabel3");

        javax.swing.GroupLayout pnAococLayout = new javax.swing.GroupLayout(pnAococ);
        pnAococ.setLayout(pnAococLayout);
        pnAococLayout.setHorizontalGroup(
            pnAococLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAococLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbAococ1)
                .addGap(94, 94, 94))
            .addGroup(pnAococLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnAococ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAococLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAococ, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnAococLayout.setVerticalGroup(
            pnAococLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAococLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAococ, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAococ1)
                .addGap(12, 12, 12)
                .addComponent(btnAococ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMenu.setForeground(new java.awt.Color(0, 0, 255));
        lbMenu.setText("MENU");

        pnAokhoac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAokhoac.setText("Xem chi tiết");
        btnAokhoac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAokhoacActionPerformed(evt);
            }
        });

        lbAokhoac1.setText("Áo khoác");

        lbAokhoac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Anh1.png"))); // NOI18N
        lbAokhoac.setText("jLabel3");

        javax.swing.GroupLayout pnAokhoacLayout = new javax.swing.GroupLayout(pnAokhoac);
        pnAokhoac.setLayout(pnAokhoacLayout);
        pnAokhoacLayout.setHorizontalGroup(
            pnAokhoacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAokhoacLayout.createSequentialGroup()
                .addGroup(pnAokhoacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAokhoacLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbAokhoac1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAokhoacLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbAokhoac, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAokhoacLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAokhoac)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnAokhoacLayout.setVerticalGroup(
            pnAokhoacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAokhoacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAokhoac, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAokhoac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAokhoac)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnAoni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbAoni1.setText("Áo nỉ");

        lbAoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Anh2.png"))); // NOI18N
        lbAoni.setText("jLabel3");

        btnAoni.setText("Xem chi tiết");
        btnAoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAoniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAoniLayout = new javax.swing.GroupLayout(pnAoni);
        pnAoni.setLayout(pnAoniLayout);
        pnAoniLayout.setHorizontalGroup(
            pnAoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAoniLayout.createSequentialGroup()
                .addGroup(pnAoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAoniLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbAoni, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAoniLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lbAoni1))
                    .addGroup(pnAoniLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnAoni)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnAoniLayout.setVerticalGroup(
            pnAoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAoniLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbAoni, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAoni1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAoni)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnAosomi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAosomi.setText("Xem chi tiết");
        btnAosomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAosomiActionPerformed(evt);
            }
        });

        lbAosomi1.setText("Áo sơ mi");

        lbAosomi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Anh3.png"))); // NOI18N
        lbAosomi.setText("jLabel3");

        javax.swing.GroupLayout pnAosomiLayout = new javax.swing.GroupLayout(pnAosomi);
        pnAosomi.setLayout(pnAosomiLayout);
        pnAosomiLayout.setHorizontalGroup(
            pnAosomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAosomiLayout.createSequentialGroup()
                .addGroup(pnAosomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAosomiLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbAosomi1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAosomiLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAosomi))
                    .addGroup(pnAosomiLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbAosomi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnAosomiLayout.setVerticalGroup(
            pnAosomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAosomiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAosomi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAosomi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAosomi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnAococ1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAococ1.setText("Xem chi tiết");
        btnAococ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAococ1ActionPerformed(evt);
            }
        });

        lbAococ2.setText("Áo cộc");

        lbAococ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Anh4.png"))); // NOI18N
        lbAococ3.setText("jLabel3");

        javax.swing.GroupLayout pnAococ1Layout = new javax.swing.GroupLayout(pnAococ1);
        pnAococ1.setLayout(pnAococ1Layout);
        pnAococ1Layout.setHorizontalGroup(
            pnAococ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAococ1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbAococ3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(pnAococ1Layout.createSequentialGroup()
                .addGroup(pnAococ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAococ1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lbAococ2))
                    .addGroup(pnAococ1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnAococ1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAococ1Layout.setVerticalGroup(
            pnAococ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAococ1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAococ3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAococ2)
                .addGap(12, 12, 12)
                .addComponent(btnAococ1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMenu1.setForeground(new java.awt.Color(0, 0, 255));
        lbMenu1.setText("MENU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(pnAosomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMenu1)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnAococ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnAoni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(pnAokhoac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(499, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnAoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbMenu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnAosomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnAococ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnAokhoac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(338, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAokhoacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAokhoacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAokhoacActionPerformed

    private void btnAoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAoniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAoniActionPerformed

    private void btnAosomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAosomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAosomiActionPerformed

    private void btnAococActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAococActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAococActionPerformed

    private void btnAococ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAococ1ActionPerformed

    }//GEN-LAST:event_btnAococ1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAococ;
    private javax.swing.JButton btnAococ1;
    private javax.swing.JButton btnAokhoac;
    private javax.swing.JButton btnAoni;
    private javax.swing.JButton btnAosomi;
    private javax.swing.JLabel lbAococ;
    private javax.swing.JLabel lbAococ1;
    private javax.swing.JLabel lbAococ2;
    private javax.swing.JLabel lbAococ3;
    private javax.swing.JLabel lbAokhoac;
    private javax.swing.JLabel lbAokhoac1;
    private javax.swing.JLabel lbAoni;
    private javax.swing.JLabel lbAoni1;
    private javax.swing.JLabel lbAosomi;
    private javax.swing.JLabel lbAosomi1;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbMenu1;
    private javax.swing.JPanel pnAococ;
    private javax.swing.JPanel pnAococ1;
    private javax.swing.JPanel pnAokhoac;
    private javax.swing.JPanel pnAoni;
    private javax.swing.JPanel pnAosomi;
    // End of variables declaration//GEN-END:variables
}
