/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.NhanVien;

/**
 *
 * @author Admin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public Menu(NhanVien nv) {
        initComponents();
        lbMenu.setText(nv.getMa());
    }

    private Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnQuanlysanpham = new javax.swing.JButton();
        lbMenu = new javax.swing.JLabel();
        btnQuanlynhanvien = new javax.swing.JButton();
        btnQuanlyhoadonchitiet = new javax.swing.JButton();
        btnQuanlyhoadon = new javax.swing.JButton();
        pnAokhoac = new javax.swing.JPanel();
        btnAokhoac = new javax.swing.JButton();
        lbAokhoac1 = new javax.swing.JLabel();
        lbAokhoac = new javax.swing.JLabel();
        pnAoni = new javax.swing.JPanel();
        lbAoni1 = new javax.swing.JLabel();
        lbAoni = new javax.swing.JLabel();
        btnAoni = new javax.swing.JButton();
        pnAosomi = new javax.swing.JPanel();
        btnAosomi = new javax.swing.JButton();
        lbAosomi1 = new javax.swing.JLabel();
        lbAosomi = new javax.swing.JLabel();
        pnAococ = new javax.swing.JPanel();
        btnAococ = new javax.swing.JButton();
        lbAococ1 = new javax.swing.JLabel();
        lbAococ = new javax.swing.JLabel();
        btnChuongtrinhkhuyenmai = new javax.swing.JButton();
        btnChitietsanpham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Quản Lý Quần Áo");

        btnQuanlysanpham.setText("Quản Lý Sản Phẩm");

        lbMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMenu.setForeground(new java.awt.Color(0, 0, 255));
        lbMenu.setText("MENU");

        btnQuanlynhanvien.setText("Quản Lý Nhân Viên");

        btnQuanlyhoadonchitiet.setText("Quản lý hóa đơn chi tiết");

        btnQuanlyhoadon.setText("Quản lý hóa đơn");
        btnQuanlyhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlyhoadonActionPerformed(evt);
            }
        });

        pnAokhoac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAokhoac.setText("Xem chi tiết");

        lbAokhoac1.setText("Áo khoác");

        lbAokhoac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/Anh1.png"))); // NOI18N
        lbAokhoac.setText("jLabel3");

        javax.swing.GroupLayout pnAokhoacLayout = new javax.swing.GroupLayout(pnAokhoac);
        pnAokhoac.setLayout(pnAokhoacLayout);
        pnAokhoacLayout.setHorizontalGroup(
            pnAokhoacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAokhoacLayout.createSequentialGroup()
                .addGroup(pnAokhoacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAokhoacLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbAokhoac1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAokhoacLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbAokhoac, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAokhoacLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAokhoac)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnAokhoacLayout.setVerticalGroup(
            pnAokhoacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAokhoacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAokhoac, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAokhoac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAokhoac)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnAoni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbAoni1.setText("Áo nỉ");

        lbAoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/Anh2.png"))); // NOI18N
        lbAoni.setText("jLabel3");

        btnAoni.setText("Xem chi tiết");
        btnAoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAoniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAoniLayout = new javax.swing.GroupLayout(pnAoni);
        pnAoni.setLayout(pnAoniLayout);
        pnAoniLayout.setHorizontalGroup(
            pnAoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAoniLayout.createSequentialGroup()
                .addGroup(pnAoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAoniLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAoni, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAoniLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbAoni1))
                    .addGroup(pnAoniLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnAoni)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnAoniLayout.setVerticalGroup(
            pnAoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAoniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAoni, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAoni1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAoni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnAosomi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAosomi.setText("Xem chi tiết");

        lbAosomi1.setText("Áo sơ mi");

        lbAosomi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/Anh3.png"))); // NOI18N
        lbAosomi.setText("jLabel3");

        javax.swing.GroupLayout pnAosomiLayout = new javax.swing.GroupLayout(pnAosomi);
        pnAosomi.setLayout(pnAosomiLayout);
        pnAosomiLayout.setHorizontalGroup(
            pnAosomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAosomiLayout.createSequentialGroup()
                .addGroup(pnAosomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAosomiLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbAosomi1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAosomiLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAosomi))
                    .addGroup(pnAosomiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAosomi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAosomiLayout.setVerticalGroup(
            pnAosomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAosomiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAosomi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAosomi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAosomi)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnAococ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAococ.setText("Xem chi tiết");

        lbAococ1.setText("Áo cộc");

        lbAococ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/Anh4.png"))); // NOI18N
        lbAococ.setText("jLabel3");

        javax.swing.GroupLayout pnAococLayout = new javax.swing.GroupLayout(pnAococ);
        pnAococ.setLayout(pnAococLayout);
        pnAococLayout.setHorizontalGroup(
            pnAococLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAococLayout.createSequentialGroup()
                .addGroup(pnAococLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAococLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAococ))
                    .addGroup(pnAococLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAococ, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAococLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbAococ1)
                .addGap(94, 94, 94))
        );
        pnAococLayout.setVerticalGroup(
            pnAococLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAococLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAococ, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAococ1)
                .addGap(12, 12, 12)
                .addComponent(btnAococ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnChuongtrinhkhuyenmai.setText("Chương trình khuyến mãi");
        btnChuongtrinhkhuyenmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuongtrinhkhuyenmaiActionPerformed(evt);
            }
        });

        btnChitietsanpham.setText("Chi tiết sản phẩm");
        btnChitietsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChitietsanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChuongtrinhkhuyenmai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanlynhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanlyhoadonchitiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanlyhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanlysanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChitietsanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnAosomi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnAokhoac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnAoni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnAococ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lbMenu)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(lbMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnAoni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnAokhoac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnChitietsanpham)
                        .addGap(98, 98, 98)
                        .addComponent(btnQuanlysanpham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuanlyhoadon)
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnAosomi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnAococ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnQuanlyhoadonchitiet)
                        .addGap(104, 104, 104)
                        .addComponent(btnQuanlynhanvien)
                        .addGap(98, 98, 98)
                        .addComponent(btnChuongtrinhkhuyenmai)))
                .addGap(31, 89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanlyhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlyhoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanlyhoadonActionPerformed

    private void btnAoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAoniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAoniActionPerformed

    private void btnChuongtrinhkhuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuongtrinhkhuyenmaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChuongtrinhkhuyenmaiActionPerformed

    private void btnChitietsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChitietsanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChitietsanphamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAococ;
    private javax.swing.JButton btnAokhoac;
    private javax.swing.JButton btnAoni;
    private javax.swing.JButton btnAosomi;
    private javax.swing.JButton btnChitietsanpham;
    private javax.swing.JButton btnChuongtrinhkhuyenmai;
    private javax.swing.JButton btnQuanlyhoadon;
    private javax.swing.JButton btnQuanlyhoadonchitiet;
    private javax.swing.JButton btnQuanlynhanvien;
    private javax.swing.JButton btnQuanlysanpham;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbAococ;
    private javax.swing.JLabel lbAococ1;
    private javax.swing.JLabel lbAokhoac;
    private javax.swing.JLabel lbAokhoac1;
    private javax.swing.JLabel lbAoni;
    private javax.swing.JLabel lbAoni1;
    private javax.swing.JLabel lbAosomi;
    private javax.swing.JLabel lbAosomi1;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JPanel pnAococ;
    private javax.swing.JPanel pnAokhoac;
    private javax.swing.JPanel pnAoni;
    private javax.swing.JPanel pnAosomi;
    // End of variables declaration//GEN-END:variables
}
